data "aws_ami" "al2023" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-*-x86_64"]
  }
}

resource "aws_key_pair" "api_gw" {
  key_name   = "${var.name}-api-gw-key"
  public_key = file(var.ssh_public_key_path)

  tags = merge(var.tags, {
    Name = "${var.name}-api-gw-key"
  })
}

resource "aws_security_group" "api_gw" {
  name        = "${var.name}-api-gw-sg"
  description = "API Gateway SG (HTTP public, SSH only from Bastion + optional operator CIDR)"
  vpc_id      = var.vpc_id

  ingress {
    description = "HTTP from internet"
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  ingress {
    description     = "SSH from Bastion only"
    from_port       = 22
    to_port         = 22
    protocol        = "tcp"
    security_groups = [var.bastion_sg_id]
  }

  dynamic "ingress" {
    for_each = var.ssh_ingress_cidrs
    content {
      description = "SSH temporary from operator CIDR"
      from_port   = 22
      to_port     = 22
      protocol    = "tcp"
      cidr_blocks = [ingress.value]
    }
  }

  egress {
    description = "All outbound"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = merge(var.tags, {
    Name = "${var.name}-api-gw-sg"
  })
}

locals {
  user_data = <<-EOF
#!/bin/bash
set -euxo pipefail
exec > >(tee /var/log/user-data.log | logger -t user-data -s 2>/dev/console) 2>&1

dnf -y update
dnf -y install nginx

# NGINX main config (routes are included from conf.d/routes.conf)
cat > /etc/nginx/nginx.conf <<'CONF'
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

events { worker_connections 1024; }

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  access_log  /var/log/nginx/access.log;
  sendfile on;
  keepalive_timeout 65;

  server {
    listen 80;

    location = / {
      return 200 "API Gateway OK. Use /auth /chat /item /search /user /delivery /notification /reputation /reservation /traceability ...\\n";
    }

    # Routes are generated by Terraform
    include /etc/nginx/conf.d/routes.conf;

    # Common proxy headers (applies to proxy_* blocks)
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
CONF

# Write routes as a separate file (supports multi-line safely)
cat > /etc/nginx/conf.d/routes.conf <<'ROUTES'
${var.routes_rendered}
ROUTES

nginx -t
systemctl enable --now nginx
systemctl restart nginx
EOF
}

resource "aws_instance" "api_gw" {
  ami                    = data.aws_ami.al2023.id
  instance_type          = var.instance_type
  subnet_id              = var.public_subnet_id
  vpc_security_group_ids = [aws_security_group.api_gw.id]
  key_name               = aws_key_pair.api_gw.key_name

  user_data = local.user_data

  # IMPORTANT: If user_data changes, replace instance so cloud-init runs again
  user_data_replace_on_change = true

  iam_instance_profile = var.instance_profile_name

  tags = merge(var.tags, {
    Name = "${var.name}-api-gateway"
  })
}

resource "aws_eip" "api_gw" {
  domain = "vpc"
  tags   = merge(var.tags, { Name = "${var.name}-api-gw-eip" })
}

resource "aws_eip_association" "api_gw" {
  allocation_id = aws_eip.api_gw.id
  instance_id   = aws_instance.api_gw.id
}
